export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED'
}

export const userConstants = {
    USER_REGISTRATION_REQUEST: 'USER_REGISTRATION_REQUEST',
    USER_REGISTRATION_SUCCESS: 'USER_REGISTRATION_SUCCESS',
    USER_REGISTRATION_FAILED: 'USER_REGISTRATION_FAILED'
}

export const productConstants = {
    GET_ALL_PRODUCT_REQUEST: 'GET_ALL_PRODUCT_REQUEST',
    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
    GET_ALL_PRODUCT_FAILURE: 'GET_ALL_PRODUCT_FAILURE'
}

export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILED: 'GET_ALL_CATEGORIES_FAILED',
    ADD_NEW_CATEGORY_REQUEST: 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE: 'ADD_NEW_CATEGORY_FAILURE',
    UPDATE_CATEGORIES_REQUEST: 'UPDATE_CATEGORIES_REQUEST',
    UPDATE_CATEGORIES_SUCCESS: 'UPDATE_CATEGORIES_SUCCESS',
    UPDATE_CATEGORIES_FAILURE: 'UPDATE_CATEGORIES_FAILURE',
    DELETE_CATEGORIES_REQUEST: 'DELETE_CATEGORIES_REQUEST',
    DELETE_CATEGORIES_SUCCESS: 'DELETE_CATEGORIES_SUCCESS',
    DELETE_CATEGORIES_FAILURE: 'DELETE_CATEGORIES_FAILURE'
}

export const getInitialDataConstants = {
    GET_ALL_INITIAL_DATA_REQUEST: 'GET_ALL_INITIAL_DATA_REQUEST',
    GET_ALL_INITIAL_DATA_SUCCESS: 'GET_ALL_INITIAL_DATA_SUCCESS',
    GET_ALL_INITIAL_DATA_FAILURE: 'GET_ALL_INITIAL_DATA_FAILURE'
}

export const pageConstants = {
    CREATE_PAGE_REQUEST: 'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS: 'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE: 'CREATE_PAGE_FAILURE'
}